### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by zahidhassan** [karthikeyan5/push-biometric-erpnext#1]
File "push_to_erpnext.py", line 221, in <module>
    error_logger = setup_logger('error_logger', '/'.join([config.LOGS_DIRECTORY, 'error.log']), logging.ERROR)
  File "push_to_erpnext.py", line 203, in setup_logger
    if not logger.hasHandlers():
AttributeError: 'Logger' object has no attribute 'hasHandlers'

**Comment by karthikeyan5** [comment]
Please use Python3. I think you are using Python2, which is not supported.
